settings:
  title: 'Status Page'
  url: 'https://status-page.mgt.moe' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: OI-Wiki
    name: oi-wiki.org
    description: '主站'
    url: 'https://oi-wiki.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
  - id: OI-Wiki-com
    name: oi-wiki.com
    description: '主站'
    url: 'https://oi-wiki.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
  - id: OI-Wiki-search
    name: OI Wiki 搜索
    description: '主站'
    url: 'https://search.oi-wiki.org:8443'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
  - id: OI-Wiki-dmit
    name: OI Wiki@DMIT
    description: 'DMIT'
    url: 'https://lax-stone.edge.ciel.dev/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
  - id: OI-Wiki-menci
    name: oi.wiki
    description: 'OI Wiki mirror by Menci'
    url: 'https://oi.wiki/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
  - id: OI-Wiki-net
    name: oi-wiki.net
    description: 'OI Wiki mirror by 琴春'
    url: 'https://oi-wiki.net/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
